config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :microposts,          only: [:create, :destroy, :show] do
    resources :likes
  end
  resources :relationships,       only: [:create, :destroy]


  

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  has_many :likes, dependent: :destroy
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy, :show]
    before_action :correct_user,   only: :destroy

    def show
      @micropost = Micropost.find(params[:id])
    end
  
    def create
      @micropost = current_user.microposts.build(micropost_params)
      if @micropost.save
        flash[:success] = "Micropost created!"
        redirect_to root_url
      else
        @feed_items = []
        render 'static_pages/home'
      end
    end
  
    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to request.referrer || root_url
    end
  
    private
  
      def micropost_params
        params.require(:micropost).permit(:content, :picture)
      end

      def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url if @micropost.nil?
      end
  end
  

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <%= image_tag micropost.picture.url if micropost.picture? %>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>

    <p><%= micropost.likes.count %> <%= (micropost.likes.count) == 1 ? 'Like' : 'Likes'%></p>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>   
  </span>
  <br>
   <span class="user"><%= link_to "Read More", micropost %></span>
</li>

app/views/microposts/show.html.erb
<h2><%= @micropost.content%> </h2>  

    
<p><%= @micropost.likes.count %> <%= (@micropost.likes.count) == 1 ? 'Like' : 'Likes'%></p>


<% pre_like = @micropost.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= button_to 'Unlike', micropost_like_path(@micropost, pre_like), method: :delete %>
<% else %>
  <%= button_to 'Like', micropost_likes_path(@micropost), method: :post %>
<% end %>